# Intro to Building a Scalable and Modular RAG System with RAG Engine in Vertex AI

<table align="left">
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/gemini/rag-engine/intro_rag_engine.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo"><br> Open in Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https:%2F%2Fraw.githubusercontent.com%2FGoogleCloudPlatform%2Fgenerative-ai%2Fmain%2Fgemini%2Frag-engine%2Fintro_rag_engine.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo"><br> Open in Colab Enterprise
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/GoogleCloudPlatform/generative-ai/main/gemini/rag-engine/intro_rag_engine.ipynb">
      <img src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo"><br> Open in Vertex AI Workbench
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/rag-engine/intro_rag_engine.ipynb">
      <img width="32px" src="https://raw.githubusercontent.com/primer/octicons/refs/heads/main/icons/mark-github-24.svg" alt="GitHub logo"><br> View on GitHub
    </a>
  </td>
</table>

<div style="clear: both;"></div>

<b>Share to:</b>

<a href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/rag-engine/intro_rag_engine.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="LinkedIn logo">
</a>

<a href="https://bsky.app/intent/compose?text=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/rag-engine/intro_rag_engine.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="Bluesky logo">
</a>

<a href="https://twitter.com/intent/tweet?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/rag-engine/intro_rag_engine.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X logo">
</a>

<a href="https://reddit.com/submit?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/rag-engine/intro_rag_engine.ipynb" target="_blank">
  <img width="20px" src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit logo">
</a>

<a href="https://www.facebook.com/sharer/sharer.php?u=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/rag-engine/intro_rag_engine.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg" alt="Facebook logo">
</a>

| Author |
| --- |
| [Holt Skinner](https://github.com/holtskinner) |

## Overview

Retrieval Augmented Generation (RAG) improves Large Language Models (LLMs) by allowing them to access and process external information sources during generation. This ensures the model's responses are grounded in factual data and avoids hallucinations.

A common problem with LLMs is that they don't understand private knowledge, that
is, your organization's data. With RAG Engine, you can enrich the
LLM context with additional private information, because the model can reduce
hallucinations and answer questions more accurately.

By combining additional knowledge sources with the existing knowledge that LLMs
have, a better context is provided. The improved context along with the query
enhances the quality of the LLM's response.

The following concepts are key to understanding Vertex AI RAG Engine. These concepts are listed in the order of the
retrieval-augmented generation (RAG) process.

1. **Data ingestion**: Intake data from different data sources. For example,
  local files, Google Cloud Storage, and Google Drive.

1. **Data transformation**: Conversion of the data in preparation for indexing. For example, data is split into chunks.

1. **Embedding**: Numerical representations of words or pieces of text. These numbers capture the
   semantic meaning and context of the text. Similar or related words or text
   tend to have similar embeddings, which means they are closer together in the
   high-dimensional vector space.

1. **Data indexing**: RAG Engine creates an index called a corpus.
   The index structures the knowledge base so it's optimized for searching. For
   example, the index is like a detailed table of contents for a massive
   reference book.

1. **Retrieval**: When a user asks a question or provides a prompt, the retrieval
  component in RAG Engine searches through its knowledge
  base to find information that is relevant to the query.

1. **Generation**: The retrieved information becomes the context added to the
  original user query as a guide for the generative AI model to generate
  factually grounded and relevant responses.

For more information, refer to the public documentation for [Vertex AI RAG Engine](https://cloud.google.com/vertex-ai/generative-ai/docs/rag-overview).

## Get started

### Install Vertex AI SDK and Google Gen AI SDK

In [ ]:
#%pip install --upgrade --quiet google-cloud-aiplatform google-genai

# Install the necessary libraries
!pip install --upgrade --quiet google-cloud-aiplatform google-genai

# Automatically restart the kernel to pick up the new library versions
import os
os.kill(os.getpid(), 9)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.9/46.9 kB 1.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 41.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 724.2/724.2 kB 42.1 MB/s eta 0:00:00

### Authenticate your notebook environment (Colab only)

If you're running this notebook on Google Colab, run the cell below to authenticate your environment.

In [1]:
import sys

if "google.colab" in sys.modules:
    from google.colab import auth

    auth.authenticate_user()

### Set Google Cloud project information and initialize Vertex AI SDK

To get started using Vertex AI, you must have an existing Google Cloud project and [enable the Vertex AI API](https://console.cloud.google.com/flows/enableapi?apiid=aiplatform.googleapis.com).

Learn more about [setting up a project and a development environment](https://cloud.google.com/vertex-ai/docs/start/cloud-environment).

See [supported regions](https://cloud.google.com/vertex-ai/generative-ai/docs/rag-engine/rag-overview#supported-regions) for location options.

In [2]:
import os

import vertexai
from google import genai

# fmt: off
PROJECT_ID = "rag-lab1"  # @param {type: "string", placeholder: "[your-project-id]", isTemplate: true} #CHANGE ME
# fmt: on
if not PROJECT_ID or PROJECT_ID == "[your-project-id]":
    PROJECT_ID = str(os.environ.get("GOOGLE_CLOUD_PROJECT"))

# See https://cloud.google.com/vertex-ai/generative-ai/docs/rag-engine/rag-overview#supported-regions for location options.
vertexai.init(project=PROJECT_ID, location="asia-northeast1")
client = genai.Client(vertexai=True, project=PROJECT_ID, location="asia-northeast1")

### Import libraries

In [3]:
from IPython.display import Markdown, display
from google.genai.types import GenerateContentConfig, Retrieval, Tool, VertexRagStore
from vertexai import rag

### Create a RAG Corpus

In [8]:
# Currently supports Google first-party embedding models
# fmt: off
#EMBEDDING_MODEL = "publishers/google/models/text-embedding-005"  # @param {type:"string", isTemplate: true}
EMBEDDING_MODEL = "publishers/google/models/text-multilingual-embedding-002"  # @param {type:"string", isTemplate: true}
# fmt: on

rag_corpus = rag.create_corpus(
    display_name="lab4.1",
    backend_config=rag.RagVectorDbConfig(
        rag_embedding_model_config=rag.RagEmbeddingModelConfig(
            vertex_prediction_endpoint=rag.VertexPredictionEndpoint(
                publisher_model=EMBEDDING_MODEL
            )
        )
    ),
)

### Check the corpus just created

In [10]:
rag.list_corpora()

ListRagCorporaPager<rag_corpora {
  name: "projects/rag-lab1/locations/asia-northeast1/ragCorpora/4611686018427387904"
  display_name: "lab4.1"
  create_time {
    seconds: 1770390300
    nanos: 440314000
  }
  update_time {
    seconds: 1770390300
    nanos: 440314000
  }
  corpus_status {
    state: ACTIVE
  }
  vector_db_config {
    rag_managed_db {
      knn {
      }
    }
    rag_embedding_model_config {
      vertex_prediction_endpoint {
        endpoint: "projects/rag-lab1/locations/asia-northeast1/publishers/google/models/text-multilingual-embedding-002"
      }
    }
  }
}
>

# Lab 4.1

### Import files from Google Cloud Storage

Remember to grant "Viewer" access to the "Vertex RAG Data Service Agent" (with the format of `service-{project_number}@gcp-sa-vertex-rag.iam.gserviceaccount.com`) for your Google Cloud Storage bucket.

For this example, we'll use a public GCS bucket containing earning reports from Alphabet.

In [11]:
#reading from a public bucket.  This bucket is hosted by someone else so it's free.
INPUT_GCS_BUCKET = [
    "gs://kmutt-rag-lab-1/RAG_LAP1/cpe_bachelor_reg.pdf",
    "gs://kmutt-rag-lab-1/RAG_LAP1/cpe_bachelor_inter.pdf",
    "gs://kmutt-rag-lab-1/RAG_LAP1/cpe_master.pdf",
    "gs://kmutt-rag-lab-1/RAG_LAP1/cpe_phd.pdf",
]
print("Start reading and chunking data in gcs bucket ", INPUT_GCS_BUCKET, " ...")

response = rag.import_files(
    corpus_name=rag_corpus.name,
    paths=INPUT_GCS_BUCKET,
    # Optional
    transformation_config=rag.TransformationConfig(
        chunking_config=rag.ChunkingConfig(chunk_size=1024, chunk_overlap=100)
    ),
    max_embedding_requests_per_min=900,  # Optional
)
print("Chunking of data in Public GCS Bucket done.")

Start reading and chunking data in gcs bucket  ['gs://kmutt-rag-lab-1/RAG_LAP1/cpe_bachelor_reg.pdf', 'gs://kmutt-rag-lab-1/RAG_LAP1/cpe_bachelor_inter.pdf', 'gs://kmutt-rag-lab-1/RAG_LAP1/cpe_master.pdf', 'gs://kmutt-rag-lab-1/RAG_LAP1/cpe_phd.pdf']  ...
Chunking of data in Public GCS Bucket done.

### Create RAG Retrieval Tool

In [12]:
# Create a tool for the RAG Corpus
rag_retrieval_tool = Tool(
    retrieval=Retrieval(
        vertex_rag_store=VertexRagStore(
            rag_corpora=[rag_corpus.name],
            similarity_top_k=10,
            vector_distance_threshold=0.5,
        )
    )
)

### Generate Content with Gemini using RAG Retrieval Tool

In [13]:
MODEL_ID = "gemini-2.5-flash"

In [14]:
def ask_rag(query, MODEL_ID, rag_retrieval_tool):
  # if query not in doc return this
  system_prompt = """Answer ONLY using the provided context.
    If the answer is not in the documents, say: 'I cannot find this in our records.'"""

  response = client.models.generate_content( # Call the generate_content method from the client's models.
      model=MODEL_ID, # Specify the generative model to use (e.g., 'gemini-2.5-pro').
      contents=f"{system_prompt}\n\nUser Query: {query}", # An example of a commented-out content query.
      config=GenerateContentConfig(tools=[rag_retrieval_tool]), # Configure content generation, including the RAG retrieval tool.
  )

  display(Markdown(f"**Q:** {query}"))
  display(Markdown(f"**A:** {response.text}"))
  print("-" * 30) # Display the generated response as Markdown.

### Chat with the RAG-enabled Model

This loop allows for continuous conversation with the generative model, leveraging the RAG retrieval tool. Type `end` to stop the chat.

In [16]:
import time

test_cases = {
    "Fact-Check": [
        "How many credits are required for the Bachelor International Program?",
        "How many credits are required for the Bachelor Regular Program?",
        "How many credits are required for the Master's Degree program?",
        "How many credits are required for the Doctor of Philosophy Programme?",
        "In which year of the Bachelor program is the internship required?",
        "How long is the internship duration for the Bachelor program?",
        "What CPE 112 learning about?",
        "What CPE 314 learning about?",
        "What is the total tuition fee for the Master Program?",
        "What CPE 624 learning about",
    ],
    "Out-of-Bounds": [
        "What is the capital of Thailand?",
        "How to cook pad thai?",
        "What is the largest country in the world?",
        "Who invented alternating current?"
    ],
    "Ambiguity (3)": [
        "How do the electives in the International Program differ from the Regular Program, and are there any courses with the same name but different course codes?",
        "Compare the admission requirements between the Master's and Doctoral programs; what are the similarities and differences?",
        "Across all levels of education (Bachelor, Master, and PhD), in which year is each 'Artificial Intelligence' related course offered in their respective programs?"
    ]
}

for category, queries in test_cases.items():
    print(f"\n=== Testing {category} ===")
    for q in queries:
        try:
            ask_rag(q, MODEL_ID, rag_retrieval_tool)
            print("Waiting for quota reset...")
            time.sleep(10)
        except Exception as e:
            if "429" in str(e):
                print("Rate limit hit! Resting for 60 seconds...")
                time.sleep(60)
            else:
                print(f"Error processing '{q}': {e}")

=== Testing Fact-Check ===

**Q:** How many credits are required for the Bachelor International Program?

**A:** The Bachelor of Engineering Program in Computer Engineering (International Program) requires a total of 130 credits.

------------------------------
Waiting for quota reset...

**Q:** How many credits are required for the Bachelor Regular Program?

**A:** The Bachelor of Engineering Program in Computer Engineering (International Program) requires a total of 130 credits.

------------------------------
Waiting for quota reset...

**Q:** How many credits are required for the Master's Degree program?

**A:** A minimum of 37 credits are required for the Master's Degree program.

------------------------------
Waiting for quota reset...

**Q:** How many credits are required for the Doctor of Philosophy Programme?

**A:** The total required credits for the Doctor of Philosophy Programme vary by plan:
*   **Plan A1:** 48 credits for students with a master's degree, without coursework.
*   **Plan B1:** 48 credits for students with a master's degree, with coursework.
*   **Plan B2:** 75 credits for students without a master's degree (with a bachelor's degree), with coursework.

------------------------------
Waiting for quota reset...

**Q:** In which year of the Bachelor program is the internship required?

**A:** I cannot find this in our records.

------------------------------
Waiting for quota reset...

**Q:** How long is the internship duration for the Bachelor program?

**A:** I cannot find this in our records.

------------------------------
Waiting for quota reset...

**Q:** What CPE 112 learning about?

**A:** CPE 112, "Programming with Data Structures," teaches computer programming with an emphasis on dynamic data structures such as dynamic arrays, linked lists, trees, graphs, and hash tables. It also covers the creation of general, reusable modules for multi-module software systems, concepts of procedural and data abstraction, encapsulation, information hiding, and object-orientation, with weekly lab sessions.

The learning outcomes include:
1.  Explaining properties and applications of various data structures.
2.  Selecting and implementing appropriate data structures and associated algorithms to efficiently solve programming problems.

------------------------------
Waiting for quota reset...

**Q:** What CPE 314 learning about?

**A:** CPE 314 (Computer Networks) is about computer network architectures and protocol stacks. It covers reliable data delivery, application layer protocols, socket programming, TCP/IP protocol suite, routing, network performance evaluation, link layer protocols, local area networks, wireless networks, and data communication over wired and wireless mediums.

------------------------------
Waiting for quota reset...

**Q:** What is the total tuition fee for the Master Program?

**A:** The total payment through the Master Program is 146,000 THB per student.

------------------------------
Waiting for quota reset...

**Q:** What CPE 624 learning about

**A:** CPE 624 is about the bases of big data engineering and the Hadoop ecosystem, including visualization, structured and unstructured databases, data services with Hive and HBase, HDFS and MapReduce, workload management (YARN), in-memory process with Spark, data integration through Flume and Sqoop, and the Solr search engine. It emphasizes system and architecture aspects as well as programming frameworks.

The learning outcomes are:
1. Understand the basic concepts of big data technology and the Hadoop ecosystem.
2. Learn how to program on the Hadoop ecosystem (interactive and batch modes).
3. Learn to integrate data from multiple sources into a single point of view and query the data through applications.

------------------------------
Waiting for quota reset...

=== Testing Out-of-Bounds ===

**Q:** What is the capital of Thailand?

**A:** I cannot find this in our records.

------------------------------
Waiting for quota reset...

**Q:** How to cook pad thai?

**A:** I cannot find this in our records.

------------------------------
Waiting for quota reset...

**Q:** What is the largest country in the world?

**A:** I cannot find this in our records.

------------------------------
Waiting for quota reset...

**Q:** Who invented alternating current?

**A:** I cannot find this in our records.

------------------------------
Waiting for quota reset...

=== Testing Ambiguity (3) ===

**Q:** How do the electives in the International Program differ from the Regular Program, and are there any courses with the same name but different course codes?

**A:** I cannot find information detailing how electives in a "Regular Program" differ from those in the "International Program", as all provided sources describe International Programs.

Yes, there are courses with the same name but different course codes:
*   In the Master's International Program, courses like "Software Engineering" (CPE 661 and CPE 650), "Computer Aided Geometric Design" (CPE 633 and CPE 630), "Multimedia Information Retrieval" (CPE 634 and CPE 651), "Human Computer Interaction" (CPE 635 and CPE 632), "Advanced Geometric Modeling" (CPE 638 and CPE 631), "Speech Processing" (CPE 644 and CPE 642), and "Data Security for Multimedia Communications" (CPE 656 and CPE 655) have the same name but different codes across curriculum revisions.
*   In the Ph.D. International Program, "Special Topic" courses are listed with different codes such as CPE 795, EEE 795, ENE 795, and INC 795.

------------------------------
Waiting for quota reset...

**Q:** Compare the admission requirements between the Master's and Doctoral programs; what are the similarities and differences?

**A:** The admission requirements for the Master's program include:
*   A Bachelor’s degree in computer engineering, computer science, applied science, electrical engineering, or an equivalent field. Applicants with degrees in related fields need approval from the admission committee.
*   Two recommendation letters.
*   English proficiency demonstrated by a TOEFL score of at least 500, or an equivalent score from another standard English test (e.g., TOEFL PBT 500, CBT 173, IBT 61; IELTS 5.5; KMUTT Test 76; CU-TEP 60). If this requirement is not met, the applicant must pass the English proficiency criteria within one year.

The provided documents describe different credit plans for the Doctoral program based on prior education (e.g., 48 credits for students with a Master's degree, or 75 credits for students with a Bachelor's degree), but do not detail other specific admission requirements such as recommendation letters or English proficiency scores for the Doctoral program.

------------------------------
Waiting for quota reset...

**Q:** Across all levels of education (Bachelor, Master, and PhD), in which year is each 'Artificial Intelligence' related course offered in their respective programs?

**A:** For Bachelor's level, the year in which each 'Artificial Intelligence' related course is offered is not specified.

For the Master's program, Artificial Intelligence related courses (CPE 640 Artificial Intelligence, CPE 641 Natural Language Processing, CPE 642 Speech Processing, CPE 643 Applied Machine Learning, and CPE 672 Advanced Artificial Intelligence) are offered as electives in Year 1 (Semester 1 and 2) and Year 2 (Semester 1 and 2).

For the PhD program, Artificial Intelligence related courses (CPE 640 Artificial Intelligence, CPE 641 Natural Language Processing, CPE 642 Speech Processing, CPE 643 Applied Machine Learning, CPE 652 Bio-inspired Computing, and CPE 654 Brain-Computer Interface) are offered as electives, but the specific year of their offering is not detailed in the provided study plan.

------------------------------
Waiting for quota reset...

In [17]:
print(f"Deleting Corpus: {rag_corpus.name}")

rag.delete_corpus(name=rag_corpus.name)

Deleting Corpus: projects/91767623906/locations/asia-northeast1/ragCorpora/4611686018427387904
Successfully deleted the RagCorpus.

#Lab4.2

### Chunk Data

In [12]:
def chunk_data():
  #reading from a public bucket.  This bucket is hosted by someone else so it's free.
  INPUT_GCS_BUCKET = (
      "gs://kmutt-rag-lab-1/RAG_LAP1/cpe_bachelor_reg.pdf"
  )
  print("Start reading and chunking data in gcs bucket ", INPUT_GCS_BUCKET, " ...")

  response = rag.import_files(
      corpus_name=rag_corpus.name,
      paths=[INPUT_GCS_BUCKET],
      # Optional
      transformation_config=rag.TransformationConfig(
          chunking_config=rag.ChunkingConfig(chunk_size=1024, chunk_overlap=100)
      ),
      max_embedding_requests_per_min=900,  # Optional
  )
  print("Chunking of data in Public GCS Bucket done.")

### Create rag tool

In [22]:
def create_rag_retrieval_tool(rag_corpus):
  # Create a tool for the RAG Corpus
  rag_retrieval_tool = Tool(
      retrieval=Retrieval(
          vertex_rag_store=VertexRagStore(
              rag_corpora=[rag_corpus.name],
              similarity_top_k=10
          )
      )
  )

  return rag_retrieval_tool

### Find Ground Truth ID

In [37]:
def ground_truth_id(query, MODEL_ID, rag_retrieval_tool):

    system_prompt = """Answer ONLY using the provided context.
    If the answer is not in the documents, say: 'I cannot find this in our records.'"""

    # เรียก LLM + RAG
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=f"{system_prompt}\n\nUser Query: {query}",
        config=GenerateContentConfig(tools=[rag_retrieval_tool]),
    )

    gt_ids = []

    print(f"คำถาม: {query}")
    print(f"คำตอบจาก AI: {response.text}\n")

    if response.candidates[0].grounding_metadata.grounding_chunks:
        chunks = response.candidates[0].grounding_metadata.grounding_chunks
        for i, chunk in enumerate(chunks):

            content_text = chunk.retrieved_context.text
            unique_chunk_id = f"{content_text[:50]}..."

            gt_ids.append(unique_chunk_id)
            # print(f"   - Found Chunk {i+1} Unique ID: {unique_chunk_id}")

    return gt_ids

### Calculate Recall@10

In [36]:
def recall_at_10(query, MODEL_ID, rag_retrieval_tool, gt_ids):
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=query,
        config=GenerateContentConfig(tools=[rag_retrieval_tool]),
    )

    retrieved_ids = []
    if response.candidates[0].grounding_metadata.grounding_chunks:
        chunks = response.candidates[0].grounding_metadata.grounding_chunks
        for c in chunks:
            text = c.retrieved_context.text.replace("\n", " ").strip()
            retrieved_ids.append(f"{text[:50]}...")

    # นับว่าใน 10 อันที่ดึงมา มีอันที่ตรงกับ Ground Truth กี่อัน
    # (โดยไม่ให้นับซ้ำตัวเดิม)
    correct_retrieved_count = 0
    for gt_id in gt_ids:
        if gt_id in retrieved_ids:
            correct_retrieved_count += 1

    # คำนวณเป็นสัดส่วน (ถ้าไม่มี GT เลยให้เป็น 0 เพื่อกัน Error)
    if len(gt_ids) == 0:
        return 0

    recall_score = correct_retrieved_count / len(gt_ids)
    return recall_score

### Create 002 Corpus RAG

In [8]:
# Currently supports Google first-party embedding models
# fmt: off
# EMBEDDING_MODEL = "publishers/google/models/text-embedding-005"  # @param {type:"string", isTemplate: true}
EMBEDDING_MODEL = "publishers/google/models/text-multilingual-embedding-002"  # @param {type:"string", isTemplate: true}
# fmt: on

rag_corpus = rag.create_corpus(
    display_name="lab4.2_corpus_002",
    backend_config=rag.RagVectorDbConfig(
        rag_embedding_model_config=rag.RagEmbeddingModelConfig(
            vertex_prediction_endpoint=rag.VertexPredictionEndpoint(
                publisher_model=EMBEDDING_MODEL
            )
        )
    ),
)

In [9]:
rag.list_corpora()

ListRagCorporaPager<rag_corpora {
  name: "projects/rag-lab1/locations/asia-northeast1/ragCorpora/5764607523034234880"
  display_name: "lab4.2_corpus_002"
  create_time {
    seconds: 1770393413
    nanos: 436995000
  }
  update_time {
    seconds: 1770393413
    nanos: 436995000
  }
  corpus_status {
    state: ACTIVE
  }
  vector_db_config {
    rag_managed_db {
      knn {
      }
    }
    rag_embedding_model_config {
      vertex_prediction_endpoint {
        endpoint: "projects/rag-lab1/locations/asia-northeast1/publishers/google/models/text-multilingual-embedding-002"
      }
    }
  }
}
rag_corpora {
  name: "projects/rag-lab1/locations/asia-northeast1/ragCorpora/576460752303423488"
  display_name: "lab4.2_corpus_002"
  create_time {
    seconds: 1770394470
    nanos: 551334000
  }
  update_time {
    seconds: 1770394470
    nanos: 551334000
  }
  corpus_status {
    state: ACTIVE
  }
  vector_db_config {
    rag_managed_db {
      knn {
      }
    }
    rag_embedding_model_config {
      vertex_prediction_endpoint {
        endpoint: "projects/rag-lab1/locations/asia-northeast1/publishers/google/models/text-multilingual-embedding-002"
      }
    }
  }
}
>

In [38]:
import pandas as pd
import time

data = [
  {"query":"หลักสูตรวิศวกรรมคอมพิวเตอร์ภาคปกติเรียนกี่หน่วยกิต?", "recall": 0},
  {"query":"วิชา CPE 402 มีวิชาบังคับก่อนไหม?", "recall": 0},
  {"query":"วิชา Database เรียนชั้นปีที่เท่าไหร่?", "recall": 0},
  {"query":"วิชา CPE 333 เรียนเกี่ยวกับอะไร?", "recall": 0},
  {"query":"ชั้นปีที่ 3 เรียนวิชาอะไรบ้าง?", "recall": 0}
]

llm_model = [
    "gemini-2.5-flash",
    "gemini-2.5-pro"
]

chunk_data()
rag_retrieval_tool = create_rag_retrieval_tool(rag_corpus)

gt_results = {}

print("--- Start Finding Ground Truth ---")
for i, item in enumerate(data):
    success = False
    while not success:
        try:
            gt_ids = ground_truth_id(item["query"], "gemini-2.5-flash", rag_retrieval_tool)
            gt_results[i] = gt_ids
            print(f"Done for Q{i+1}")
            success = True
            time.sleep(15)
        except Exception as e:
            if "429" in str(e):
                print("Quata Limit sleep 45s...")
                time.sleep(45)
            else:
                print(f"Error : {e}")
                break

results = []

for llm_name in llm_model:
    print(f"\n--- Testing Embedding 002 with {llm_name} ---")
    scores = []

    for i in range(len(data)):
        success = False
        while not success:
            try:
                # Calculate Recall@10k
                score = recall_at_10(data[i]["query"], llm_name, rag_retrieval_tool, gt_results[i])
                scores.append(score)
                print(f"Q{i+1} Recall: {score}")
                success = True
                time.sleep(15)
            except Exception as e:
                if "429" in str(e):
                    print("Quata Limit sleep 45s")
                    time.sleep(45)
                else:
                    print(f"Error: {e}")
                    success = True
                    scores.append(0)

    overall = sum(scores) / len(scores)
    row = ['002', llm_name]
    results.append(row + scores + [overall])

# สร้าง DataFrame
df1 = pd.DataFrame(results, columns=["Embedding", "Model", "Q1", "Q2", "Q3", "Q4", "Q5", "Overall"])
display(df1)

Start reading and chunking data in gcs bucket  gs://kmutt-rag-lab-1/RAG_LAP1/cpe_bachelor_reg.pdf  ...
Chunking of data in Public GCS Bucket done.
--- Start Finding Ground Truth ---
คำถาม: หลักสูตรวิศวกรรมคอมพิวเตอร์ภาคปกติเรียนกี่หน่วยกิต?
คำตอบจาก AI: หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์ (ภาคปกติ) มีจำนวนหน่วยกิตรวมตลอดหลักสูตร 130 หน่วยกิต

Done for Q1
คำถาม: วิชา CPE 402 มีวิชาบังคับก่อนไหม?
คำตอบจาก AI: I cannot find this in our records.

Done for Q2
คำถาม: วิชา Database เรียนชั้นปีที่เท่าไหร่?
คำตอบจาก AI: วิชา Database Systems (CPE 241) หรือ ระบบฐานข้อมูล จะเรียนในชั้นปีที่ 2 ภาคการศึกษาที่ 2

Done for Q3
คำถาม: วิชา CPE 333 เรียนเกี่ยวกับอะไร?
คำตอบจาก AI: วิชา CPE 333 (ระบบปฏิบัติการ) เรียนเกี่ยวกับทฤษฎีระบบปฏิบัติการ การจัดการหน่วยความจำ การจัดการการประมวลผล การจัดการหน่วยนำเข้าและส่งออก และการจัดการสารสนเทศ รวมถึงเรื่องภาษาควบคุมงาน ตัวแปลภาษาแอสแซมบลี ตัวดึงและเชื่อมโปรแกรม ตัวอย่างของระบบปฏิบัติการ คอมไพเลอร์ อินเตอร์พรีเตอร์ และโปรแกรมอรรถประโยชน์ต่างๆ

ผลลัพธ์การเรียนรู้ของวิชานี้คือสามารถอธิบายแนวคิดและส่วนประกอบในระบบปฏิบัติการ และอธิบายการออกแบบและฟังก์ชันการทำงานในโค้ดเคอร์เนล Linux เบื้องต้นได้

Done for Q4
คำถาม: ชั้นปีที่ 3 เรียนวิชาอะไรบ้าง?
คำตอบจาก AI: ในชั้นปีที่ 3 มีรายวิชาดังต่อไปนี้

**สำหรับภาคการศึกษาที่ 1:**
*   CPE 301 ประเด็นความเป็นมืออาชีพด้านวิศวกรรมคอมพิวเตอร์
*   CPE 333 ระบบปฏิบัติการ
*   CPE 334 วิศวกรรมซอฟต์แวร์
*   CPE 371 วิศวกรรมข้อมูลขนาดใหญ่ (สำหรับหลักสูตรนานาชาติ) หรือ CPE 342 การเรียนรู้ของเครื่อง (สำหรับหลักสูตรปกติ)
*   GEN 241 ความงดงามแห่งชีวิต
*   PRE 380 เศรษฐศาสตร์วิศวกรรม
*   GEN xxx วิชาเลือกหมวดวิชาศึกษาทั่วไป 1 (สำหรับหลักสูตรนานาชาติ) หรือ GEN 101 พลศึกษา (สำหรับหลักสูตรปกติ)

**สำหรับภาคการศึกษาที่ 2:**
*   CPE 301 ประเด็นความเป็นมืออาชีพด้านวิศวกรรมคอมพิวเตอร์ (สำหรับหลักสูตรปกติ)
*   CPE 313 สัญญาณและระบบเชิงเส้น (สำหรับหลักสูตรปกติ)
*   CPE 314 เครือข่ายคอมพิวเตอร์
*   CPE 324 ระบบสมองกลฝังตัว (สำหรับหลักสูตรปกติ)
*   CPE 343 ธุรกิจอัจฉริยะ (สำหรับหลักสูตรนานาชาติ)
*   GEN 351 การบริหารจัดการยุคใหม่และภาวะผู้น า
*   CPE 3xx วิชาเลือกทางวิศวกรรมคอมพิวเตอร์ 1
*   GEN xxx วิชาเลือกหมวดวิชาศึกษาทั่วไป 2 (สำหรับหลักสูตรนานาชาติ)
*   XXX xxx วิชาเลือกหมวดวิชาเลือกเสรี 1 (สำหรับหลักสูตรนานาชาติ)

Done for Q5

--- Testing Embedding 002 with gemini-2.5-flash ---
Q1 Recall: 0.2
Q2 Recall: 0.3
Q3 Recall: 0.3
Q4 Recall: 0.5
Q5 Recall: 0.3

--- Testing Embedding 002 with gemini-2.5-pro ---
Q1 Recall: 0.2
Q2 Recall: 0.3
Q3 Recall: 0.3
Q4 Recall: 0.5
Q5 Recall: 0.3

  Embedding             Model   Q1   Q2   Q3   Q4   Q5  Overall
0       002  gemini-2.5-flash  0.2  0.3  0.3  0.5  0.3     0.32
1       002    gemini-2.5-pro  0.2  0.3  0.3  0.5  0.3     0.32

In [39]:
print(f"Deleting Corpus: {rag_corpus.name}")

rag.delete_corpus(name=rag_corpus.name)

Deleting Corpus: projects/91767623906/locations/asia-northeast1/ragCorpora/576460752303423488
Successfully deleted the RagCorpus.

### Create RAG Corpus 005

In [40]:
# Currently supports Google first-party embedding models
# fmt: off
EMBEDDING_MODEL = "publishers/google/models/text-embedding-005"  # @param {type:"string", isTemplate: true}
# EMBEDDING_MODEL = "publishers/google/models/text-multilingual-embedding-002"  # @param {type:"string", isTemplate: true}
# fmt: on

rag_corpus = rag.create_corpus(
    display_name="lab4.2_corpus_002",
    backend_config=rag.RagVectorDbConfig(
        rag_embedding_model_config=rag.RagEmbeddingModelConfig(
            vertex_prediction_endpoint=rag.VertexPredictionEndpoint(
                publisher_model=EMBEDDING_MODEL
            )
        )
    ),
)

In [41]:
import pandas as pd
import time

data = [
  {"query":"หลักสูตรวิศวกรรมคอมพิวเตอร์ภาคปกติเรียนกี่หน่วยกิต?", "recall": 0},
  {"query":"วิชา CPE 402 มีวิชาบังคับก่อนไหม?", "recall": 0},
  {"query":"วิชา Database เรียนชั้นปีที่เท่าไหร่?", "recall": 0},
  {"query":"วิชา CPE 333 เรียนเกี่ยวกับอะไร?", "recall": 0},
  {"query":"ชั้นปีที่ 3 เรียนวิชาอะไรบ้าง?", "recall": 0}
]

llm_model = [
    "gemini-2.5-flash",
    "gemini-2.5-pro"
]

chunk_data()
rag_retrieval_tool = create_rag_retrieval_tool(rag_corpus)

gt_results = {}

print("--- Start Finding Ground Truth ---")
for i, item in enumerate(data):
    success = False
    while not success:
        try:
            gt_ids = ground_truth_id(item["query"], "gemini-2.5-flash", rag_retrieval_tool)
            gt_results[i] = gt_ids
            print(f"Done for Q{i+1}")
            success = True
            time.sleep(15)
        except Exception as e:
            if "429" in str(e):
                print("Quata Limit sleep 45s...")
                time.sleep(45)
            else:
                print(f"Error : {e}")
                break

results = []

for llm_name in llm_model:
    print(f"\n--- Testing Embedding 005 with {llm_name} ---")
    scores = []

    for i in range(len(data)):
        success = False
        while not success:
            try:
                # Calculate Recall@10k
                score = recall_at_10(data[i]["query"], llm_name, rag_retrieval_tool, gt_results[i])
                scores.append(score)
                print(f"Q{i+1} Recall: {score}")
                success = True
                time.sleep(15)
            except Exception as e:
                if "429" in str(e):
                    print("Quata Limit sleep 45s")
                    time.sleep(45)
                else:
                    print(f"Error: {e}")
                    success = True
                    scores.append(0)

    overall = sum(scores) / len(scores)
    row = ['002', llm_name]
    results.append(row + scores + [overall])


df2 = pd.DataFrame(results, columns=["Embedding", "Model", "Q1", "Q2", "Q3", "Q4", "Q5", "Overall"])

Start reading and chunking data in gcs bucket  gs://kmutt-rag-lab-1/RAG_LAP1/cpe_bachelor_reg.pdf  ...
Chunking of data in Public GCS Bucket done.
--- Start Finding Ground Truth ---
คำถาม: หลักสูตรวิศวกรรมคอมพิวเตอร์ภาคปกติเรียนกี่หน่วยกิต?
คำตอบจาก AI: I cannot find this in our records.

Done for Q1
คำถาม: วิชา CPE 402 มีวิชาบังคับก่อนไหม?
คำตอบจาก AI: วิชา CPE 402 มีวิชาบังคับก่อนคือ CPE 401 โครงงานวิศวกรรมคอมพิวเตอร์1

Done for Q2
คำถาม: วิชา Database เรียนชั้นปีที่เท่าไหร่?
คำตอบจาก AI: วิชา Database (CPE 241 ระบบฐานข้อมูล) เรียนในชั้นปีที่ 2 ภาคการศึกษาที่ 2

Done for Q3
คำถาม: วิชา CPE 333 เรียนเกี่ยวกับอะไร?
คำตอบจาก AI: วิชา CPE 333 (Operating Systems) เรียนเกี่ยวกับ:

*   ทฤษฎีระบบดำเนินงาน: การจัดการหน่วยความจำ, การจัดลำดับการประมวล, การจัดการหน่วยนำเข้าและส่งออก, และการจัดการสารสนเทศ
*   ประเด็นเกี่ยวกับภาษาควบคุมงาน, ตัวแปลภาษาแอสแซมบลี, ตัวดึงและเชื่อมโปรแกรม
*   ตัวอย่างกรณีศึกษาของระบบดำเนินงาน, คอมไพเลอร์, อินเทอร์พรีเตอร์ และโปรแกรมอรรถประโยชน์

Done for Q4
คำถาม: ชั้นปีที่ 3 เรียนวิชาอะไรบ้าง?
คำตอบจาก AI: I cannot find this in our records.

Done for Q5

--- Testing Embedding 002 with gemini-2.5-flash ---
Q1 Recall: 0.4
Q2 Recall: 0.6
Q3 Recall: 0.3
Q4 Recall: 0.5
Q5 Recall: 0.4

--- Testing Embedding 002 with gemini-2.5-pro ---
Q1 Recall: 0.4
Q2 Recall: 0.6
Q3 Recall: 0.3
Q4 Recall: 0.5
Q5 Recall: 0.4

TypeError: concat() got an unexpected keyword argument 'ignore_idex'

In [45]:
df = pd.concat([df1,df2], ignore_index=True)
display(df)

  Embedding             Model   Q1   Q2   Q3   Q4   Q5  Overall
0       002  gemini-2.5-flash  0.2  0.3  0.3  0.5  0.3     0.32
1       002    gemini-2.5-pro  0.2  0.3  0.3  0.5  0.3     0.32
2       002  gemini-2.5-flash  0.4  0.6  0.3  0.5  0.4     0.44
3       002    gemini-2.5-pro  0.4  0.6  0.3  0.5  0.4     0.44

In [46]:
print(f"Deleting Corpus: {rag_corpus.name}")

rag.delete_corpus(name=rag_corpus.name)

Deleting Corpus: projects/91767623906/locations/asia-northeast1/ragCorpora/7493989779944505344
Successfully deleted the RagCorpus.